package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mercredi 19 décembre 2018 10 h 03 CET
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
